RUN_STRINGS = (
    "Ahora me ves, ahora no." "ε=ε=ε=ε=┌(;￣▽￣)┘",
    "¡Regresa aquí!",
    "REEEEEEEEEEEEEEEEEE!!!!!!!",
    "¡Cuidado con la pared!",
    "No me dejes solo con ellos!!",
    "¡Tienes compañía!",
    "Chotto matte!",
    "Yare yare daze",
    "*Naruto run activated*",
    "*Nezuko run activated*",
    "¡Oye, hazte responsable de lo que acabas de hacer!",
    "Que las probabilidades estén siempre a tu favor.",
    "Corran todos, acaban de lanzar una bomba 💣💣",
    "Y desaparecieron para siempre, para nunca más ser vistos.",
    "Cuenta la leyenda que siguen corriendo.",
    "Hasta la vista, baby.",
    "Ah, qué desperdicio.  Me gustó ese.",
    "Como diría el Doctor... ¡CORRE!",
)

GIFS = [
    "CgACAgQAAx0CSVUvGgAC7KpfWxMrgGyQs-GUUJgt-TSO8cOIDgACaAgAAlZD0VHT3Zynpr5nGxsE",
    "CgACAgUAAx0CU_rCTAABAjdgX1s4NVaeCls6YaH3p43vgdCRwQIAAqsAA4P_MFUYQhyoR-kgpRsE",
    "CgACAgUAAx0CU_rCTAABAjdSX1s3fq5iEJ64YeQLKI8cD7CSuSEAAlUBAAJu09hW5iqWB0hTPD4bBA",
]

KISS_STRINGS = (
      "CgACAgQAAxkBAAIJPGP5izDQbwT2eGsXV9kNkW_LdRG6AAJDAwACCtq0UnD5NHX-_bnLLgQ",
      "CgACAgQAAxkBAAIJQWP5lj67FVNoBa0KedBLs46K9b3dAAIqAwAC7fW1UlgAAT0Xcp5WDC4E",
      "CgACAgQAAxkBAAIJQmP5lkA-ui2We9n6lPR-vrBz9N7cAAIYAwACEaq0UhPEsg-FDta3LgQ",
      "CgACAgEAAxkBAAIJQ2P5lkQvvE2L2UaC11eNHaWR_ImeAAKYAQACZVyxRPxsgj1x193ALgQ",
      "CgACAgEAAxkBAAIJRGP5lkiK-NKarv6k3QzvIExoODm_AAJPAAORAAEhRbkpBZqh8Dh9LgQ",
      "CgACAgQAAxkBAAIJRWP5lk6H4CqydT6aehwMsr9TkbVtAAJDAgACCS0sUnf29wwXM-W_LgQ",
      "CgACAgQAAxkBAAIKD2P6BVrAuOxODWL10Mbb052tlhz1AALKAgACi53cUhjSbY1sEECCLgQ",
      "CgACAgQAAxkBAAIKEGP6BV5aa5Widc0YsMauG7Q7blMgAAKSAQACQme1UkPy16nF49ZILgQ",
      "CgACAgEAAxkBAAIKEWP6BXZha0293UbEnUlumF3uIL2oAAIPAQAC0m04RLX2zapLfHfqLgQ",
      "CgACAgQAAxkBAAIKEmP6BY8Hs8KClKMji-BKWlQv3E2JAALfAgACsEz9UR8WemxzEt7uLgQ",
      "CgACAgEAAxkBAAIKE2P6BZcE6egdsy5tK5ZbD17MgLosAAI2AQACb9-QRbOoktkjJSfELgQ",
      "CgACAgQAAxkBAAIKFGP6BZnIr3qkG_hDgQtP9F3SijbrAAIuAwAC8bC0UuULWj97WXn8LgQ",
      "CgACAgQAAxkBAAIKF2P6BagWs5CDW6KVr9n795SrAAGEkAAC4QEAAukkFFNnVkOuQPEdxC4E",
      "CgACAgQAAxkBAAIKGWP6BbOgznXuZSmCcN18UlrAKWhkAAJ0AAPVZ-1Ri0BEaqZfWi4uBA",
      "CgACAgQAAxkBAAIKGmP6BbXQMpeJmRuR8KsLP9n7f-vJAAJFAgAC-rKUUhq4dVla145GLgQ",
      "CgACAgIAAxkBAAIKG2P6BcJzF1-2kldqJSGYHnZxkkARAAIDEQACkq_pSGAG5cXtkZ-ZLgQ",
      "CgACAgEAAxkBAAIKIGP6BdaijND8iy5t_ci056eYoBO0AAK8AQAC5zgYRyhtr-oUn3vaLgQ",
      "CgACAgQAAxkBAAIKIWP6BeAy1VrE2kPYFvaToZO6Mxm6AAIEAgAC48pcUzxrw9KFLgQzLgQ",
      "CgACAgQAAxkBAAIKImP6BePA3oeI4ItmB3JON4BaysFRAAKtAANqz5RQMI-9JJCJw8wuBA",
      "CgACAgEAAxkBAAIKamP6CZZYXUibt9Gg-XUKlik8W-xmAAI7AgACBKr4RCbUidhgPSHALgQ",
      "CgACAgQAAxkBAAIKbGP6CamB1AfKxcawVua8hQ9Hj9lRAALUDAACn1EYU26wk2EDBqbELgQ",
      "CgACAgQAAxkBAAIKbmP6Cb9CLiKtP4yYuC4bcdxkome0AAJOAwACTxelUo2LC6TKKTFALgQ",
      "CgACAgQAAxkBAAIKVWP6CKEKFlYHrWXswyxfUOCl0qFXAAJeAgACXtO9USmOF8BoTpGSLgQ",
      "CgACAgQAAxkBAAIKVmP6CKgBDM18tVuqoLGwfUqy2VLjAALMBgACO6NYUmWiAWd3gBhVLgQ",
      "CgACAgEAAxkBAAIKWGP6CLmwK1yb-kHvw4R10UOJlH9pAAKoAQACH8mYRJmLbcJV-cBNLgQ",
      "CgACAgQAAxkBAAIKWWP6CLohd9Jsr282DXg3wz5JazeTAAK1AgAC8Fi9Upq_13Z2lu1jLgQ",
      "CgACAgQAAxkBAAIKUmP6B8TdMuhdyHrTK8TAtDsykrG-AAIbAwAC0ykFU4YZR5TY_Vv3LgQ",
      "CgACAgQAAxkBAAIJ_2P6BPy3xaHHD57V67M7jtRMR66KAALkAgACV1ENU2jXqTT4yB6uLgQ",
      "CgACAgQAAxkBAAIKDGP6BUrFHTZ1fpwReYByiG1My559AAJOAwACTxelUo2LC6TKKTFALgQ",
      "CgACAgQAAxkBAAIKFWP6BZ43f-gx4fsXsXy3l4UnGa-XAAJdAwACkh4FU5VYPHlL2OfzLgQ",
      "CgACAgQAAxkBAAIKHWP6Bc2Wqv-haKGPamV3gBWUoNGNAALbAgAC4ssNU1JdhY_PqpqpLgQ",
      "CgACAgQAAxkBAAIKMWP6BjSxmFJNx9qwB_MUevDXkMfIAAJoAwACYgQNUslO5uyFMNIxLgQ",
      "CgACAgQAAxkBAAIKPGP6Bl6O8Eci6bz7FtjyqNgDSsY1AALmAgACHCMVU3gT9ewrP325LgQ",
      "CgACAgQAAxkBAAIKRWP6Bov8UTEbl1GSheafq5vzDNF7AALZAgAC22gMUz5DgMHmWmKcLgQ",
      "CgACAgQAAxkBAAIKSGP6BrD5tHsvuYnkz5tD9DWVhh5iAAK4AgACUdMVU8StPcTt3ehkLgQ",
      "CgACAgQAAxkBAAIKS2P6BvZpw6wQfc8ObIcOxkF75IjeAAILAwACj7wMU4QjQ8z7bpw1LgQ",
      "CgACAgQAAxkBAAIKTGP6BxEszzMa7ii3rr0HWQvK_nKsAAI6AwACQisFUwqrSpl8Aeo3LgQ",
      "CgACAgQAAxkBAAIKWmP6CR6aXdZeQt7lVjlNXK6zR1f9AAIMAwAC6McMU-MkfzXTEgFSLgQ",
      
)
   
SLAP_FALLEN_TEMPLATES = (
    "Golpéame una vez más y te silenciaré.",
    "Deja de abofetearme. REEEEEEEEEEEEEEE.",
    [
        "Te estoy silenciando por un minuto.",  # normal reply
        "Deja de abofetearme solo porque no puedo silenciarte. REEEEEEEEEEE.",  # reply to admin
        "tmute",  # command
        "Shut up!",
        "Silence!",
    ],
)

SLAP_TEMPLATES = (
    "{user2} fue asesinado por arte de magia.",
    "{user2} murió de hambre #momento_latam.",
    "{user2} fue arrojado al vacío por {user1}.",
    "{user2} se desmayó.",
    "{user2} se ha quedado sin Pokémon utilizables! {user2} derrotado!.",
    "{user2} se ha quedado sin Pokémon utilizables! {user2} desmayado!.",
    "{user2} fue devorado por Godzila.",
    "El melón de {user2} fue cortado por {user1}.",
    "{user2} fue silenciado por {user1}.",
    "{user2} jugó hot-potato con una granada.",
    "{user2} fue acuchillado por {user1}.",
    "{user2} comió una granada.",
    "{user2} es lo que hay para la cena!",
    "{user2} fue despedido por {user1}.",
    "{user1} envió spam al correo electrónico de {user2}.",
    "{user1} encriptado con RSA {user2} y eliminó la clave privada.",
    "{user1} puso a {user2} en la friendzone.",
    "{user1} abofetea a {user2} con una solicitud de eliminación de DMCA!",
    "{user2} recibe una llamada a domicilio del doctor {user1}.",
    "{user1} decapitado por {user2}.",
    "{user2} fue apedreado...por una multitud enojada.",
    "{user1} demandó a {user2}",
    "{user2} fue noqueado de un golpe por {usuer1}.",
    "{user1} envió a {user2} al agujero de la memoria.",
    "{user2} fue un error. - {user1}",
    "{user2} fue despedido.",
    "{user1} {hits} {user2} ¡con un bate!",
    "{user1} {hits} {user2} ¡con una patada Taijutsu!",
    "{user1} {hits} {user2} ¡con Guantes-X!",
    "{user1} {hits} {user2} ¡con un Puñetazo Jet!",
    "{user1} {hits} {user2} ¡con una Pistola Jet!",
    "{user1} {hits} {user2} ¡con una United States of Smash!",
    "{user1} {hits} {user2} ¡con un Smash de Detroit!",
    "{user1} {hits} {user2} ¡con un Texas Smash!",
    "{user1} {hits} {user2} ¡con un California Smash!",
    "{user1} {hits} {user2} ¡con un Smash de New Hampshire!",
    "{user1} {hits} {user2} ¡con un Smash de Missouri!",
    "{user1} {hits} {user2} ¡con un Carolina Smash!",
    "{user1} {hits} {user2} ¡con una Pistola King Kong!",
    "{user1} {hits} {user2} con un bate de béisbol - ¡uno de metal!.",
    "*Puñetazos serios a {user2}*.",
    "*Puñetazos normales a {user2}*.",
    "*Puñetazos normales consecutivos a {user2}*.",
    "*Puñetazos normales consecutivos a dos manos a {user2}*",
    "*Ignora a {user2} para dejarlos morir de vergüenza*",
    "*señala a {user2}* ¿Qué le pasa a este descarado... niño perdido?",
    "*Golpea a {user2} con un Tornado de Fuego*.",
    "{user1} pokes {user2} in the eye!",
    "{user1} ¡pincha a {user2} en los costados!",
    "¡{user1} pincha a {user2}!",
    "¡{user1} pincha a {user2} con una aguja!",
    "¡{user1} pincha a {user2} con un bolígrafo!",
    "¡{user1} pincha a {user2} con una pistola paralizante!",
    "¡{user2} es secretamente un Furro!",
    "¡Hola a todos! {user1} me está pidiendo que sea malo!",
    "( ･_･)ﾉ⌒●~* (･.･;) <-{user2}",
    "Toma esto {user2}\n(ﾉﾟДﾟ)ﾉ ))))●~*",
    "Aquí {user2} sostiene este\n(｀・ω・)つ ●~＊",
    "( ・_・)ノΞ●~*  {user2}\nDieeeee!!.",
    "( ・∀・)ｒ鹵~<≪巛;ﾟДﾟ)ﾉn*Bug sprays {user2}*.",
    "( ﾟДﾟ)ﾉ占~<巛巛巛.\n-{user2} ¡Que peste!",
    "( う-´)づ︻╦̵̵̿╤── \(˚☐˚”)/ {user2}.",
    "{user1} {hits} {user2} con un {item}",
    "{user1} {hits} {user2} en la cara con un {item}.",
    "{user1} {hits} {user2} un poco con un {item}.",
    "{user1} {throws} un {item} a {user2}",
    "{user1} coge un {item} y lo {throws} a la cara de {user2}",
    "{user1} lanza un {item} en la dirección general de {user2}",
    "{user1} comienza a abofetear {user2} tontamente con un {item}.",
    "{user1} inmoviliza a {user2} y le {hits} repetidamente con un {item}",
    "{user1} agarra un {item} y {hits} {user2} con él",
    "{user1} ata a {user2} a una silla y {throws} un {item}",
    "{user1} dio un empujón amistoso para ayudar a {user2} a aprender a nadar en la lava.",
    "{user1} intimidó a {user2}.",
    "Nyaan se comió la pierna de {user2}. *nomnomnom*",
    "{user1} {throws} una bola maestra a {user2}, la resistencia es inútil",
    "{user1} golpea a {user2} con un rayo de acción...bbbbbb (ง・ω・)ง ====*",
    "{user1} ara ara's {user2}.",
    "{user1} ora ora's {user2}.",
    "{user1} muda muda's {user2}.",
    "¡{user2} se convirtió en una referencia a Jojo!",
    "{user1} golpea a {user2} con {item}.",
    "¡Asalto 2!... ¿Listos?... ¡¡¡Luchen!!!",
    "WhoPixel golpeará a {user2} hasta el infinito y más allá",
    "{user2} se comió un murciélago y descubrió una nueva enfermedad",
    "{user1} dobló a {user2} en un avión de papel",
    "{user1} sirvió a {user2} sopa de murciélago",
    "{user2} fue enviado a su hogar, el planeta de los simios",
    "{user1} echó a {user2} de un tren en marcha",
    "{user2} acaba de matar al perro de John Wick.",
    "{user1} realizó un hechizo Avada Kedavra sobre {user2}.",
    "{user1} sometió a {user2} a un horno ardiente.",
    "Sakura Haruno acaba de volverse más útil que {user2}",
    "{user1} desconectó el soporte vital de {user2}",
    "{user1} suscribió a {user2} a 5 años de mal internet.",
    "¿Sabes qué es peor que los chistes de papá? {user2}!",
    "{user1} cogió todas las galletas de {user2}.",
    "¡{user2} wa mou.......Shindeiru! - {user1}",
    "{user2} ¡perdió su pieza de carrera!", # No game no life reference
    "Cállate {user2}, sólo eres {user2}.", # Sin juego sin referencia de vida
    "{user1} golpea a {user2} con Aka shi anse!", # No hay referencia de juego ni de vida
    "@NeoTheKitty araña a {user2}", # Gato mascota de Pixels - @NeoTheKitty
    "Majin buu se comió a {user2}", # Dbz
    "Goblin slayer mata a {user2}", 
)

PAT_TEMPLATES = (
    "{user1} da palmaditas en la cabeza a {user2}",
    "*frota suavemente la cabeza de {user2}",
    "*{user1} mofumofusca la cabeza de {user2}",
    "*{user1} desordena la cabeza de {user2}",
    "*{user1} frota intensamente la cabeza de {user2}*",
    "*La waifu de {user2} le acaricia la cabeza*",
    "*{user2}'s got free headpats*",
    "¡No hay palmaditas para {user2}!",
    "¡Oh, no! Nos hemos quedado sin palmaditas",
    "¡Esta es una zona designada sin palmadas!",
    "¡Sin palmadas para {user2}!",
    "¡{user1} mima a {user2} con palmadas en la cabeza!",
    "¡{user2} recibió una palmada gratis!",
    "{user1} le da palmadas en la cabeza a {user2} mientras le da una almohada",
    "{user1} acaricia agresivamente a {user2}",
    "{user1} acaricia suavemente la cabeza de {user2}",
    "Palmadita, palmadita, palmadita",
    "{user2} no pudo escapar de las palmaditas en la cabeza de {user1}",
    "{user2}.exe ha dejado de funcionar",
    "{user1} frota a {user2} en el cuello",
    "Debe... extorsionar... CABEZAZOS",
    "{user1} le da una palmadita en la cabeza a {user2}",
    "{user1} palmea inesperadamente a {user2}",
    "{user1} palmea a {user2} con consentimiento, ¿quizás?",
    "¡Pat pat, {user2} honto kawaii ne!",
    "{user1} headpats {user2} at 420apm",
    "{user1} bellyrubs {user2}",
    "{user1} acaricia amistosamente a {user2}",
    "{user2} usa HEADPATS? O KAWAII KOTO",
    "*headpats.gif se intensifica para {user2}*",
    "(*´ω´(*｀ω｀)",
    "(ｏ・_・)ノ”(ᴗ_ ᴗ。)",
    "(*￣▽￣)ノ”(- -*)",
    "(っ´ω`)ﾉ(╥ω╥)",
    "( ´Д｀)ﾉ(´･ω･`) ﾅﾃﾞﾅﾃﾞ",
)
    
PAT_GIFS = (
    "CgACAgQAAxkBAALRX19Xs7tBdOH1gQwS_rglVRkTbgVYAAKEAgACmQn9UWlyGa_xy9_aGwQ",
    "CgACAgEAAxkBAALRYF9Xs8EnhsDfDpld3ILoqTbzDmwxAAJFAAOJxjlHECanwn69E5QbBA",
)

PAT_STICKERS = (
    "CAACAgQAAxkBAALRWV9Xs4HH0XaXfhZe-jWaZoXfs-IsAAJYAwACdDgSEHYOt4KvL02oGwQ",
    "CAACAgQAAxkBAALRXF9Xs6XmIeDbnoL1wiDky0TdX-CvAAKKAQAC1TMzC9A3CtiT2rqVGwQ",
)

PING_STRING = ("ɪ ᴀᴍ ᴀʟɪᴠᴇ ʙᴀʙʏ! 🖤",)

ITEMS = (
   "sartén de hierro fundido",
    "gato enfadado",
    "bate de cricket",
    "bastón de madera",
    "pala",
    "tostadora",
    "libro",
    "ordenador portátil",
    "pollo de goma",
    "murciélago con púas",
    "roca pesada",
    "pedazo de tierra",
    "tonelada de ladrillos",
    "rasengan",
    "bomba espiritual",
    "100-Type Guanyin Bodhisattva",
    "rasenshuriken",
    "Murasame",
    "ban",
    "chunchunmaru",
    "Kubikiribōchō",
    "rasengan",
    "kat volador esférico",
)

THROW = (
    "lanza",
    "tira",
    "arroja",
    "lanza",
)

HIT = (
    "golpea a",
    "golpea a",
    "abofetea a",
    "golpea a",
    "golpea a",
    "palmea a",
)

EYES = [
    ["⌐■", "■"],
    [" ͠°", " °"],
    ["⇀", "↼"],
    ["´• ", " •`"],
    ["´", "`"],
    ["`", "´"],
    ["ó", "ò"],
    ["ò", "ó"],
    ["⸌", "⸍"],
    [">", "<"],
    ["Ƹ̵̡", "Ʒ"],
    ["ᗒ", "ᗕ"],
    ["⟃", "⟄"],
    ["⪧", "⪦"],
    ["⪦", "⪧"],
    ["⪩", "⪨"],
    ["⪨", "⪩"],
    ["⪰", "⪯"],
    ["⫑", "⫒"],
    ["⨴", "⨵"],
    ["⩿", "⪀"],
    ["⩾", "⩽"],
    ["⩺", "⩹"],
    ["⩹", "⩺"],
    ["◥▶", "◀◤"],
    ["◍", "◎"],
    ["/͠-", "┐͡-\\"],
    ["⌣", "⌣”"],
    [" ͡⎚", " ͡⎚"],
    ["≋"],
    ["૦ઁ"],
    ["  ͯ"],
    ["  ͌"],
    ["ළ"],
    ["◉"],
    ["☉"],
    ["・"],
    ["▰"],
    ["ᵔ"],
    [" ﾟ"],
    ["□"],
    ["☼"],
    ["*"],
    ["`"],
    ["⚆"],
    ["⊜"],
    [">"],
    ["❍"],
    ["￣"],
    ["─"],
    ["✿"],
    ["•"],
    ["T"],
    ["^"],
    ["ⱺ"],
    ["@"],
    ["ȍ"],
    ["  "],
    ["  "],
    ["x"],
    ["-"],
    ["$"],
    ["Ȍ"],
    ["ʘ"],
    ["Ꝋ"],
    [""],
    ["⸟"],
    ["๏"],
    ["ⴲ"],
    ["◕"],
    ["◔"],
    ["✧"],
    ["■"],
    ["♥"],
    [" ͡°"],
    ["¬"],
    [" º "],
    ["⨶"],
    ["⨱"],
    ["⏓"],
    ["⏒"],
    ["⍜"],
    ["⍤"],
    ["ᚖ"],
    ["ᴗ"],
    ["ಠ"],
    ["σ"],
    ["☯"],
]

MOUTHS = [
    ["v"],
    ["ᴥ"],
    ["ᗝ"],
    ["Ѡ"],
    ["ᗜ"],
    ["Ꮂ"],
    ["ᨓ"],
    ["ᨎ"],
    ["ヮ"],
    ["╭͜ʖ╮"],
    [" ͟ل͜"],
    [" ͜ʖ"],
    [" ͟ʖ"],
    [" ʖ̯"],
    ["ω"],
    [" ³"],
    [" ε "],
    ["﹏"],
    ["□"],
    ["ل͜"],
    ["‿"],
    ["╭╮"],
    ["‿‿"],
    ["▾"],
    ["‸"],
    ["Д"],
    ["∀"],
    ["!"],
    ["人"],
    ["."],
    ["ロ"],
    ["_"],
    ["෴"],
    ["ѽ"],
    ["ഌ"],
    ["⏠"],
    ["⏏"],
    ["⍊"],
    ["⍘"],
    ["ツ"],
    ["益"],
    ["╭∩╮"],
    ["Ĺ̯"],
    ["◡"],
    [" ͜つ"],
]

EARS = [
    ["q", "p"],
    ["ʢ", "ʡ"],
    ["⸮", "?"],
    ["ʕ", "ʔ"],
    ["ᖗ", "ᖘ"],
    ["ᕦ", "ᕥ"],
    ["ᕦ(", ")ᕥ"],
    ["ᕙ(", ")ᕗ"],
    ["ᘳ", "ᘰ"],
    ["ᕮ", "ᕭ"],
    ["ᕳ", "ᕲ"],
    ["(", ")"],
    ["[", "]"],
    ["¯\\_", "_/¯"],
    ["୧", "୨"],
    ["୨", "୧"],
    ["⤜(", ")⤏"],
    ["☞", "☞"],
    ["ᑫ", "ᑷ"],
    ["ᑴ", "ᑷ"],
    ["ヽ(", ")ﾉ"],
    ["\\(", ")/"],
    ["乁(", ")ㄏ"],
    ["└[", "]┘"],
    ["(づ", ")づ"],
    ["(ง", ")ง"],
    ["⎝", "⎠"],
    ["ლ(", "ლ)"],
    ["ᕕ(", ")ᕗ"],
    ["(∩", ")⊃━☆ﾟ.*"],
]

TOSS = ("Cara", "Cruz")

EIGHTBALL = [
    "🟢 A mi modo de ver, sí",
    "🟡 Vuelve a preguntar más tarde",
    "🟡 Mejor no te lo digo ahora",
    "🟡 No puedo predecirlo ahora",
    "🟡 Concéntrate y vuelve a preguntar",
    "🟡 No cuentes con ello",
    "🟢 Es seguro",
    "🟢 Es decididamente así.",
    "🟢 Lo más probable",
    "🔴 Mi respuesta es no.",
    "🔴 Mis fuentes dicen que no",
    "🔴 Perspectivas no muy buenas.",
    "🟢 Outlook bueno",
    "🟡 Respuesta confusa, inténtalo de nuevo",
    "🟢 Los indicios apuntan a que sí",
    "🔴 Muy dudoso",
    "🟢 Sin duda",
    "🟢 Sí",
    "🟢 Sí, sin duda",
    "🟢 Puedes confiar en ello",
]

DECIDE = ("Si.", "No.", "Tal vez.")

TABLE = (
    "(╯°□°）╯彡 ┻━┻",
"Me quedé sin mesas, pediré más",
   "Ve a hacer algún trabajo en lugar de voltear mesas",
)


TRUTH_STRINGS = (

"¿Cuándo fue la última vez que mentiste?",
"¿Qué es lo peor que has hecho en el trabajo?",
"¿Cuándo fue la última vez que lloraste?",
"¿Y la última vez que te reíste?",
"¿Cuál es tu mayor miedo?",
"¿Cuál es tu mayor fantasía?",
"¿Tienes algún fetiche?",
"¿Quién es la última persona que has buscado en Instagram?",
"¿Y la última a la que has seguido?",
"¿Qué es lo que te alegra que tu familia no sepa de ti?",
"¿Has engañado alguna vez a alguien?",
"¿Cuál es el lugar más extraño en el que has orinado?",
"¿Cuál es el lugar más extraño en el que has defecado?",
"¿Qué es lo peor que has hecho?",
"¿Qué es lo más extraño que has comido?",
"¿Cuál es tu problema en las relaciones?",
"¿Cuál es el secreto que nunca le has contado a nadie?",
"¿Tienes algún talento oculto?",
"¿Quién fue tu primer amor 'celebrity'?",
"¿Qué opinas del poliamor?",
"¿Cuál es la peor experiencia íntima que has tenido?",
"¿Cuál es la mejor experiencia íntima que has tenido?",
"¿Has copiado alguna vez en un examen?",
"Si fueras a participar en un 'reality show', ¿cuál sería?",
"¿Cuál es la mayor borrachera que has tenido?",
"¿Has infringido alguna vez la ley?",
"¿Has robado algo de alguna tienda?",
"¿Qué es lo más vergonzoso que has hecho?",
"¿Cuál es tu mayor inseguridad?",
"¿Has seguido siendo amigo de alguien porque te beneficiaba más allá de la amistad?",
"¿Cuál es el mayor error que has cometido?",
"¿Qué es lo más desagradable que has hecho?",
"¿A quién te gustaría besar en esta habitación?",
"¿Qué es lo que odias que la gente sepa de ti?",
"¿Qué es lo peor que te han hecho?",
"¿Qué es lo mejor que alguien ha hecho por ti?",
"¿Has tenido alguna vez un enfrentamiento con la ley?",
"¿Cuál es tu peor hábito?",
"¿Qué es lo más vergonzoso que has hecho en un taxi?",
"¿Alguna vez has suplicado a alguien? ¿El qué?",
"¿Qué es lo peor que le has dicho a alguien?",
"¿Has orinado alguna vez en la ducha?",
"¿Cuál es el sueño más extraño que has tenido?",
"¿Y el más placentero?",
"¿Te han pillado alguna vez haciendo algo que no debías?",
"¿Cuál es la peor cita que has tenido?",
"¿Cuál es la mejor cita que has tenido?",
"¿Qué pasó en la última noche de fiesta que has tenido?",
"¿Cuál es tu mayor arrepentimiento?",
"¿Cuál es la mayor idea errónea sobre ti?",
"¿Has dicho alguna vez algo de lo que te arrepientas sobre alguien de esta sala?",
"¿Qué es lo que te gustaría que la gente supiera de ti?",
"¿Cuál es el lugar más extraño donde has tenido sexo?",
"¿Por qué se rompió tu última relación?",
"¿Has mentido alguna vez para salir de una mala cita?",
"¿Cuál es el mayor problema en el que te has metido?",
"¿Cuándo fue la última vez que tuviste sexo fuera de casa?",
"¿Qué es lo peor en lo que has mentido?",
"¿Qué es en lo que desearías haber mentido?",
"¿Cuál es el mejor consejo que te han dado?",
"¿Qué es lo máximo que has gastado en una noche de fiesta?",
"¿Has devuelto o regalado alguna vez un regalo?",
"Nombra alguna vez que creas que has sido un mal compañero.",
"¿Cuál es tu placer culpable?",
"¿Qué es lo que solo haces cuando estás solo?",
"Si tuvieras que volver con un ex, ¿a quién elegirías?",
"Si tuvieras que eliminar a un amigo de tu vida, ¿quién sería?",
"¿Tienes un amigo favorito?",
"¿Tienes un hermano favorito?",
"¿Cuál es el rumor más extraño que has escuchado sobre ti?",
"¿Qué es lo que más te excita?",
"¿Cuál es tu combinación de alimentos asquerosos favorita?",
"¿Cuál es la razón más tonta por la que has abandonado un club antes de tiempo?",
"¿Qué has comprado que haya sido el mayor despilfarro de dinero?",
"Si pudieras intercambiar tu vida con alguien de esta sala, ¿quién sería?",
"¿Cada cuánto te masturbas?",
"¿Ves porno?",
"¿Has tenido una relación 'poliamorosa'?",
"¿Has comido insectos una vez?",
"¿Has dejado a alguna cita plantada?",
"¿Has hecho ghosting?",
"¿Alguna vez has salido con zapatillas de andar por casa a la calle?",
"¿Alguna vez has salido de casa sin ropa interior?",
"¿Alguna vez te has quedado sin dinero antes de llegar a fin de mes?",
"¿Te has escapado de casa para ir de fiesta?",
"¿Te has liado con la pareja de un amigo?",
"¿Has mentido a tu jefe/profesor alguna vez?",
"¿Has mentido sobre tu edad para sacar algo a cambio?",
"¿Te has liado con tu ex teniendo pareja?",
"¿Cuál ha sido la mayor locura que has hecho con tu pelo?",
"¿Cuál es la broma más pesada que has hecho?",
"¿Alguna vez has olido tus genitales?",
"¿Y la más pesada que te han gastado?",
"¿Te has acostado con alguien y lo has ignorado después?",
"¿Qué es que más te gusta de tu físico?",
"¿Qué es lo que menos te gusta de tu físico?",
"¿Qué es lo más loco que has comprado en un viaje?",
"¿Has comido algo de la basura?",
"¿Has comido algo caducado?",
"¿Has recogido algún mueble de la calle?",
"¿Te has ido de algún sitio sin pagar?",
"¿Guardas en la mesita de noche juguetes sexuales?",
"¿Tendrías un lío con alguien de la política?",
"¿Qué película odias por encima de todo?",
"¿Qué serie has dejado a medias porque no la soportabas?",
"¿Tienes miedo a las arañas?",
"¿Has tenido sexo en un avión?",
"¿Has hecho pis en la playa?",
"¿Te has colado en un concierto sin entrada?",
"¿Has pedido un autógrafo a alguien famoso?",

)

DARE_STRINGS = (

"Escribir a un número desconocido y pedir una pizza. Insistir aunque la persona diga que no es una pizzería.",
"Salir al balcón y grabarse gritando :¡chupitos gratis en mi casa!",
"Poner de perfil una de tus peores selfies",
"Publicar un estado de WhatsApp vergonzoso",
"Mandar una captura de pantalla en la que se vea que le confiesas tu amor a una persona de su elección",
"Poner la foto de perfil de uno de tus amigos durante 2 días",
"Jugar a *cuánta batería te queda*. Este juego consiste en que dependiendo de la batería que tengas, tendrás que enfrentarte a un reto u otro. 90% o más de batería: tienes que decir el nombre de tu crush. 80 - 90 %: contar un secreto. 60 - 80 %: describir la relación que tengas con los miembros del grupo a través de el título de una canción o película. 40 - 60%: decir cuál fue tu opinión sobre otra persona cuando os conocisteis. 20 - 40%: decir qué sientes por x persona del grupo 10 - 20%: envía por el grupo las últimas 5 fotos que te hayas hecho. Menos de 10%: cuenta un chiste.",
"Comparte con el resto del grupo un vídeo subido de tono que te guste.",
"Haz una lista con las partes del cuerpo que más te gustan de otra persona del grupo (Nombrar a la persona).",
"Grábate cantando una canción vergonzosa que te guste.",
"Hazte una foto haciendo la peineta y mándasela a quien digan tus amigos.",
"Aféitate los brazos y envíame una foto.",
"Grábate en video cantando una canción y subela al grupo.",
"Mezcla una gota de cada condimento de tu casa y bébetelo/cometelo (enviar video como prueba).",
"Manda un mensaje a alguien con quien no has hablado en al menos 1 año y haz una captura de pantalla.",
"¡Intenta lamerte tu propio pie! (enviar video)",
"Grabáte un audio gimiendo y envíalo al grupo.",
"Envía un mensaje de texto a la persona que te gusta y pídele una cita.",
"Llena la bañera y métete con la ropa que llevas puesta (enviar foto).",
"Escoge el tercer usuario de tu historial de mensajes y envíale un mensaje con un poema tonto.",
"Envíale una foto de My Little Pony a tu ex, si no tienes descargala (envia captura al grupo cuando te responda).",
"Sueltate el pelo y envia una foto al grupo.",
"Métete cubitos de hielo en los pantalones e intenta sacudírtelos y envíame un vídeo.",
"Grábate un vídeo haciendo un baile loco y publícalo en las redes sociales.",
"Pregúntale a un admin en otro grupo si tiene puede recargar con un peso (envia captura).",
"Envía una captura de pantalla de tus mensajes con la última persona a la que enviaste un mensaje.",
"Cepíllate los dientes con mantequilla de cacahuete u otro condimento y envía una foto.",
"Hazte una foto muy poco favorecedora y conviértela en tu foto de perfil durante un día entero.",
"Envía una captura de pantalla de tu galería de selfies.",
"Sube a tu cama y baila muy mal hasta que pase un minuto (enviar video).",
"Envía un compañero de clases o trabajo y escribe :Veo gente muerta (enviar captura de pantalla).",
"Envía un selfie a tu ex.",
"Finge ser un gato durante 1 minuto y envía un vídeo.",
"Encuentra lo más picante que haya en tu casa y cómete una cucharada entera.",
"Graba un vídeo haciendo tus cosas más raras.",
"Ponte ropa del sexo opuesto y graba un vídeo intentando actuar como un chico/chica.",
"Crea un tutorial de maquillaje realmente malo de cinco minutos y subelo al grupo.",


)
